name: Deploy Post Action
description: Run post actions required on the end of each deploy
author: Robson Andrade

inputs:
  has-package:
    description: has docker images
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Get repo name
      shell: bash
      run: |
        export repo_name=`echo "${{ github.repository }}" | awk -F '/' '{print $2}'`
        echo "repo_name=${repo_name}" >> $GITHUB_ENV

    - uses: actions/delete-package-versions@v5
      if: ${{ inputs.has-package == true }}
      with:
        package-name: ${{ env.repo_name }}
        package-type: 'container'
        min-versions-to-keep: 10
        delete-only-untagged-versions: 'true'
